version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - misspell
    - rowserrcheck
    - staticcheck
    - unused
  exclusions:
    generated: disable
    presets:
      - std-error-handling

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: disable
