version: "2"

linters:
  default: none
  enable:
    - copyloopvar
    - govet
    - ineffassign
    - misspell
    - unused
  exclusions:
    generated: disable

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: disable
